apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-moonstone-moonstone-fe
  name: moonstone-fe
  namespace: moonstone
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-moonstone-moonstone-fe
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-moonstone-moonstone-fe
    spec:
      containers:
        - image: 192.168.6.96:8098/moonstone-fe:0.<BUILD_TAG>
          imagePullPolicy: Always
          name: moonstone-fe
          ports:
            - containerPort: 80
              protocol: TCP
