apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: moonstone-fe
  namespace: moonstone
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-moonstone-moonstone-fe
  type: NodePort
